import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth/middleware';

const translations = {
  en: {
    title: 'LinkedIn Optimization Report',
    generatedOn: 'Generated on',
    profileScore: 'Profile Score',
    outOf100: 'out of 100',
    headlines: 'Recommended Headlines',
    aboutSummary: 'Recommended About Summary',
    experience: 'Experience Improvements',
    skills: 'Skills Recommendations',
    skillsToAdd: 'Skills to Add',
    original: 'Original',
    improved: 'Improved',
    at: 'at',
    atsType: 'ATS-Friendly',
    keywordType: 'Keyword-Rich',
    recruiterType: 'Recruiter-Attractive',
    corporateTone: 'Corporate Tone',
    conversationalTone: 'Conversational Tone',
    leadershipTone: 'Leadership Tone',
    footerLine1: 'Generated by CVin LinkedIn Optimizer',
    footerLine2: 'Optimize your professional presence with AI-powered insights',
    completeness: 'Completeness',
    keywords: 'Keywords',
    summary: 'Summary',
    achievements: 'Achievements',
    branding: 'Branding',
  },
  ar: {
    title: 'تقرير تحسين LinkedIn',
    generatedOn: 'تم الإنشاء في',
    profileScore: 'درجة الملف الشخصي',
    outOf100: 'من 100',
    headlines: 'العناوين الموصى بها',
    aboutSummary: 'ملخص "نبذة عني" الموصى به',
    experience: 'تحسينات الخبرات',
    skills: 'توصيات المهارات',
    skillsToAdd: 'المهارات المقترح إضافتها',
    original: 'الأصلي',
    improved: 'المحسّن',
    at: 'في',
    atsType: 'متوافق مع ATS',
    keywordType: 'غني بالكلمات المفتاحية',
    recruiterType: 'جذاب للمجندين',
    corporateTone: 'نبرة رسمية',
    conversationalTone: 'نبرة تحاورية',
    leadershipTone: 'نبرة قيادية',
    footerLine1: 'تم إنشاؤه بواسطة محسن LinkedIn من CVin',
    footerLine2: 'حسّن حضورك المهني برؤى الذكاء الاصطناعي',
    completeness: 'الاكتمال',
    keywords: 'الكلمات المفتاحية',
    summary: 'الملخص',
    achievements: 'الإنجازات',
    branding: 'العلامة الشخصية',
  }
};

export const POST = requireAuth(async (request: NextRequest, user) => {
  try {
    const isPremium = user.subscriptionTier && user.subscriptionTier !== 'free';
    if (!isPremium) {
      return NextResponse.json(
        { error: 'PDF export is a premium feature' },
        { status: 403 }
      );
    }

    const body = await request.json();
    const { report, language = 'en' } = body;

    if (!report) {
      return NextResponse.json(
        { error: 'Report data is required' },
        { status: 400 }
      );
    }

    const t = translations[language as keyof typeof translations] || translations.en;
    const isRtl = language === 'ar';
    const dir = isRtl ? 'rtl' : 'ltr';
    const fontFamily = isRtl 
      ? "'Cairo', 'Noto Sans Arabic', 'Inter', sans-serif" 
      : "'Inter', sans-serif";
    const dateLocale = isRtl ? 'ar-SA' : 'en-US';

    const generateHtmlReport = () => {
      const getTypeLabel = (type: string) => {
        if (type === 'ats') return t.atsType;
        if (type === 'keyword') return t.keywordType;
        return t.recruiterType;
      };

      const getToneLabel = (tone: string) => {
        if (tone === 'corporate') return t.corporateTone;
        if (tone === 'conversational') return t.conversationalTone;
        return t.leadershipTone;
      };

      const getScoreLabel = (key: string) => {
        const labelMap: Record<string, string> = {
          completeness: t.completeness,
          keywords: t.keywords,
          summary: t.summary,
          experience: t.experience,
          achievements: t.achievements,
          branding: t.branding,
        };
        return labelMap[key] || key.replace(/([A-Z])/g, ' $1');
      };

      const headlinesHtml = report.headlines?.map((h: any, i: number) => `
        <div style="margin-bottom: 15px; padding: 15px; background: #f8f9fa; border-radius: 8px;">
          <span style="background: ${h.type === 'ats' ? '#dcfce7' : h.type === 'keyword' ? '#dbeafe' : '#f3e8ff'}; 
                       color: ${h.type === 'ats' ? '#166534' : h.type === 'keyword' ? '#1e40af' : '#7c3aed'};
                       padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600;">
            ${getTypeLabel(h.type)}
          </span>
          <p style="margin-top: 10px; font-size: 16px; color: #1f2937;">${h.text}</p>
        </div>
      `).join('') || '';

      const aboutHtml = report.aboutVariations?.map((a: any) => `
        <div style="margin-bottom: 15px; padding: 15px; background: #f8f9fa; border-radius: 8px;">
          <span style="background: ${a.tone === 'corporate' ? '#dbeafe' : a.tone === 'conversational' ? '#dcfce7' : '#f3e8ff'}; 
                       color: ${a.tone === 'corporate' ? '#1e40af' : a.tone === 'conversational' ? '#166534' : '#7c3aed'};
                       padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600;">
            ${getToneLabel(a.tone)}
          </span>
          <p style="margin-top: 10px; font-size: 14px; color: #4b5563; white-space: pre-wrap;">${a.text}</p>
        </div>
      `).join('') || '';

      const experienceHtml = report.experienceImprovements?.map((exp: any) => `
        <div style="margin-bottom: 20px; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
          <div style="background: #f3f4f6; padding: 10px 15px;">
            <strong style="color: #1f2937;">${exp.position}</strong>
            <span style="color: #6b7280;"> ${t.at} ${exp.company}</span>
          </div>
          <div style="display: flex; ${isRtl ? 'flex-direction: row-reverse;' : ''}">
            <div style="flex: 1; padding: 15px; border-${isRtl ? 'left' : 'right'}: 1px solid #e5e7eb;">
              <p style="font-size: 12px; color: #9ca3af; text-transform: uppercase; margin-bottom: 8px;">${t.original}</p>
              <p style="font-size: 13px; color: #6b7280;">${exp.original}</p>
            </div>
            <div style="flex: 1; padding: 15px; background: #f0fdf4;">
              <p style="font-size: 12px; color: #166534; text-transform: uppercase; margin-bottom: 8px;">${t.improved}</p>
              <p style="font-size: 13px; color: #1f2937;">${exp.improved}</p>
            </div>
          </div>
        </div>
      `).join('') || '';

      const skillsHtml = `
        <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 20px; ${isRtl ? 'flex-direction: row-reverse;' : ''}">
          ${report.skillsToAdd?.map((s: any) => `
            <span style="background: ${s.priority === 'high' ? '#fef2f2' : s.priority === 'medium' ? '#fefce8' : '#f3f4f6'}; 
                         color: ${s.priority === 'high' ? '#991b1b' : s.priority === 'medium' ? '#854d0e' : '#374151'};
                         padding: 6px 14px; border-radius: 20px; font-size: 13px;">
              ${s.skill}
            </span>
          `).join('') || ''}
        </div>
      `;

      const scoreHtml = `
        <div style="text-align: center; margin-bottom: 30px;">
          <div style="width: 120px; height: 120px; border-radius: 50%; border: 8px solid ${
            report.profileScore?.overall >= 80 ? '#22c55e' : 
            report.profileScore?.overall >= 60 ? '#eab308' : '#ef4444'
          }; display: inline-flex; align-items: center; justify-content: center; flex-direction: column;">
            <span style="font-size: 36px; font-weight: bold; color: #1f2937;">${report.profileScore?.overall || 0}</span>
            <span style="font-size: 12px; color: #6b7280;">${t.outOf100}</span>
          </div>
        </div>
        <div>
          ${Object.entries(report.profileScore || {}).filter(([k]) => k !== 'overall').map(([key, value]) => `
            <div style="margin-bottom: 12px;">
              <div style="display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 4px; ${isRtl ? 'flex-direction: row-reverse;' : ''}">
                <span style="color: #4b5563;">${getScoreLabel(key)}</span>
                <span style="font-weight: 600; color: #1f2937;">${value}%</span>
              </div>
              <div style="height: 8px; background: #e5e7eb; border-radius: 4px; overflow: hidden; ${isRtl ? 'direction: rtl;' : ''}">
                <div style="height: 100%; width: ${value}%; background: ${
                  Number(value) >= 80 ? '#22c55e' : Number(value) >= 60 ? '#eab308' : '#ef4444'
                }; border-radius: 4px; ${isRtl ? 'float: right;' : ''}"></div>
              </div>
            </div>
          `).join('')}
        </div>
      `;

      return `
<!DOCTYPE html>
<html dir="${dir}" lang="${language}">
<head>
  <meta charset="UTF-8">
  <title>${t.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Cairo:wght@400;500;600;700&family=Noto+Sans+Arabic:wght@400;500;600;700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { 
      font-family: ${fontFamily}; 
      line-height: 1.8; 
      color: #1f2937; 
      padding: 40px; 
      max-width: 800px; 
      margin: 0 auto; 
      direction: ${dir};
      text-align: ${isRtl ? 'right' : 'left'};
    }
    h1 { font-size: 28px; color: #0c4a6e; margin-bottom: 8px; }
    h2 { font-size: 20px; color: #1f2937; margin: 30px 0 15px; padding-bottom: 8px; border-bottom: 2px solid #06b6d4; }
    h3 { font-size: 16px; color: #374151; margin-bottom: 10px; }
    .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 1px solid #e5e7eb; }
    .date { font-size: 14px; color: #6b7280; }
    .section { margin-bottom: 30px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${t.title}</h1>
    <p class="date">${t.generatedOn} ${new Date(report.generatedAt).toLocaleDateString(dateLocale, { 
      year: 'numeric', month: 'long', day: 'numeric' 
    })}</p>
  </div>

  <div class="section">
    <h2>${t.profileScore}</h2>
    ${scoreHtml}
  </div>

  <div class="section">
    <h2>${t.headlines}</h2>
    ${headlinesHtml}
  </div>

  <div class="section">
    <h2>${t.aboutSummary}</h2>
    ${aboutHtml}
  </div>

  <div class="section">
    <h2>${t.experience}</h2>
    ${experienceHtml}
  </div>

  <div class="section">
    <h2>${t.skills}</h2>
    <h3>${t.skillsToAdd}</h3>
    ${skillsHtml}
  </div>

  <div class="footer">
    <p>${t.footerLine1}</p>
    <p>${t.footerLine2}</p>
  </div>
</body>
</html>
      `;
    };

    const htmlContent = generateHtmlReport();

    try {
      const puppeteer = require('puppeteer-core');

      const browser = await puppeteer.launch({
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        executablePath: '/nix/store/qa9cnw4v5xkxyip6mb9kxqfq1z4x2dx1-chromium-138.0.7204.100/bin/chromium',
        headless: true,
      });

      const page = await browser.newPage();
      await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' }
      });

      await browser.close();

      return new NextResponse(pdfBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="linkedin-optimization-report.pdf"`,
        },
      });

    } catch (puppeteerError) {
      console.error('Puppeteer PDF generation failed, falling back to HTML:', puppeteerError);
      
      const htmlBuffer = Buffer.from(htmlContent, 'utf-8');
      
      return new NextResponse(htmlBuffer, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="linkedin-optimization-report.html"`,
        },
      });
    }

  } catch (error: any) {
    console.error('LinkedIn report export error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to export report' },
      { status: 500 }
    );
  }
});
